"""create activity logs table

Revision ID: 52c2b9e4e46e
Revises: 1f4a23832aea
Create Date: 2026-07-30 11:26:39.381258

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "52c2b9e4e46e"
down_revision: str | Sequence[str] | None = "1f4a23832aea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "entity_type",
            sa.Enum(
                "customer",
                "user",
                name="entity_type",
            ),
            nullable=False,
        ),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "created",
                "updated",
                "deactivated",
                name="activity_action",
            ),
            nullable=False,
        ),
        sa.Column("performed_by", sa.String(length=36), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("activity_logs")
    # ### end Alembic commands ###
